// Shared seed content, ported from the old MongoDB-based project's seed.js
// (word lists + one sample crossword), reshaped for the Firestore schema
// used by ../src/services/api.js (creatorId/creatorName instead of a
// populated `creator`, plus likes/solved arrays).

export const SEED_USER = {
    email: 'admin@starcross.seed',
    password: 'SeedAdmin123!',
    userName: 'Admin',
}

export const SEED_WORD_LISTS = [
    {
        title: 'חיות',
        description: 'רשימה של חיות',
        words: [
            { solution: 'חתול', definition: 'חיית מחמד פרוותית' },
            { solution: 'כלב', definition: 'חברו הטוב של האדם' },
            { solution: 'פיל', definition: 'היונק היבשתי הגדול ביותר' },
            { solution: 'אריה', definition: 'מלך החיות' },
            { solution: 'נמר', definition: 'חתול גדול עם פסים שחורים' },
            { solution: "ג'ירפה", definition: 'החיה הגבוהה ביותר בעולם' },
            { solution: 'זברה', definition: 'סוס עם פסים שחור-לבן' },
            { solution: 'קוף', definition: 'יונק פיקח עם זנב ארוך' },
            { solution: 'תנין', definition: 'זוחל מסוכן שחי במים וביבשה' },
            { solution: 'דולפין', definition: 'יונק ימי אינטליגנטי וידידותי' },
            { solution: 'כריש', definition: 'דג טורף עם שורות שיניים חדות' },
            { solution: 'לוויתן', definition: 'היונק הימי הגדול ביותר' },
            { solution: 'צבי', definition: 'חיה עם שריון על הגב' },
            { solution: 'ינשוף', definition: 'ציפור לילה חכמה' },
            { solution: 'נשר', definition: 'ציפור טרף גדולה' },
            { solution: 'דב', definition: 'יונק גדול שאוהב דבש' },
            { solution: 'שועל', definition: 'יונק קטן ופיקח עם פרווה אדמדמה' },
            { solution: 'זאב', definition: 'קרוב משפחה של הכלב שחי בלהקות' },
            { solution: 'גמל', definition: 'בעל חיים מדברי עם דבשת' },
            { solution: 'סוס', definition: 'חיית משא ורכיבה נאמנה' },
            { solution: 'פרה', definition: 'חיית משק שמייצרת חלב' },
            { solution: 'כבשה', definition: 'בעל חיים עם צמר רך' },
            { solution: 'עז', definition: 'בעל חיים הררי שאוהב לטפס' },
            { solution: 'תרנגול', definition: 'העוף שמכריז על הזריחה' },
            { solution: 'תוכי', definition: 'ציפור צבעונית שמסוגלת לחקות דיבור' },
            { solution: 'פינגווין', definition: 'עוף חסר יכולת תעופה שחי בקור' },
            { solution: 'עטלף', definition: 'היונק המעופף היחיד' },
            { solution: 'לטאה', definition: 'זוחל קטן ומהיר' },
            { solution: 'ארנב', definition: 'יונק קטן עם אוזניים ארוכות' },
            { solution: "צ'יטה", definition: 'בעל החיים היבשתי המהיר ביותר' },
        ],
    },
    {
        title: 'מדינות',
        description: 'רשימה של מדינות',
        words: [
            { solution: 'ישראל', definition: 'מדינה במזרח התיכון' },
            { solution: 'צרפת', definition: 'מדינה באירופה' },
            { solution: 'ארצות הברית', definition: 'מדינה בצפון אמריקה עם 50 מדינות' },
            { solution: 'סין', definition: 'המדינה המאוכלסת ביותר בעולם' },
            { solution: 'הודו', definition: 'מדינה בדרום אסיה עם אוכלוסייה עצומה' },
            { solution: 'רוסיה', definition: 'המדינה הגדולה ביותר בעולם בשטח' },
            { solution: 'ברזיל', definition: 'המדינה הגדולה ביותר בדרום אמריקה' },
            { solution: 'גרמניה', definition: 'מדינה במרכז אירופה עם כלכלה חזקה' },
            { solution: 'קנדה', definition: 'מדינה בצפון אמריקה עם שטח עצום ואוכלוסייה קטנה יחסית' },
            { solution: 'יפן', definition: 'מדינת איים במזרח אסיה עם תרבות עשירה' },
            { solution: 'איטליה', definition: 'מדינה באירופה הידועה בהיסטוריה, אומנות ואוכל' },
            { solution: 'מצרים', definition: 'מדינה בצפון אפריקה עם היסטוריה פרעונית עשירה' },
            { solution: 'בריטניה', definition: 'מדינה באירופה הכוללת את אנגליה, סקוטלנד, וויילס וצפון אירלנד' },
            { solution: 'ספרד', definition: 'מדינה בדרום אירופה הידועה בפלמנקו' },
            { solution: 'אוסטרליה', definition: 'מדינה שהיא גם יבשת' },
            { solution: 'ארגנטינה', definition: 'מדינה בדרום אמריקה עם תשוקה לכדורגל' },
            { solution: 'תאילנד', definition: 'מדינה בדרום מזרח אסיה עם חופים מרהיבים' },
            { solution: 'דרום אפריקה', definition: 'מדינה בקצה הדרומי של אפריקה' },
            { solution: 'מקסיקו', definition: 'מדינה בצפון אמריקה הידועה בטקילה' },
            { solution: 'טורקיה', definition: 'מדינה החולשת בין אירופה לאסיה' },
            { solution: 'יוון', definition: 'מדינה בדרום אירופה עם היסטוריה עתיקה' },
            { solution: 'שוודיה', definition: 'מדינה בצפון אירופה' },
            { solution: 'נורבגיה', definition: 'מדינה סקנדינבית עם פיורדים' },
            { solution: 'פינלנד', definition: 'מדינה בצפון אירופה' },
            { solution: 'דנמרק', definition: 'מדינה בצפון אירופה' },
            { solution: 'פורטוגל', definition: 'מדינה בדרום-מערב אירופה' },
            { solution: 'פולין', definition: 'מדינה במזרח אירופה' },
            { solution: "צ'כיה", definition: 'מדינה במרכז אירופה' },
            { solution: 'בלגיה', definition: 'מדינה במערב אירופה' },
            { solution: 'שווייץ', definition: 'מדינה במרכז אירופה' },
            { solution: 'הולנד', definition: 'מדינה באירופה' },
            { solution: 'אוסטריה', definition: 'מדינה באירופה' },
            { solution: 'הונגריה', definition: 'מדינה במרכז אירופה' },
            { solution: 'רומניה', definition: 'מדינה במזרח אירופה' },
            { solution: 'בולגריה', definition: 'מדינה במזרח אירופה' },
            { solution: 'סעודיה', definition: 'מדינה במזרח התיכון' },
            { solution: 'איחוד האמירויות', definition: 'מדינה במפרץ הפרסי' },
            { solution: 'קטאר', definition: 'מדינה קטנה במפרץ הפרסי' },
            { solution: 'מרוקו', definition: 'מדינה בצפון אפריקה' },
            { solution: "אלג'יריה", definition: 'המדינה הגדולה ביותר באפריקה' },
            { solution: 'ניגריה', definition: 'המדינה המאוכלסת ביותר באפריקה' },
            { solution: 'קניה', definition: 'מדינה במזרח אפריקה עם חיות בר' },
            { solution: 'אתיופיה', definition: 'מדינה במזרח אפריקה' },
            { solution: 'קולומביה', definition: 'מדינה בדרום אמריקה עם קפה מצוין' },
            { solution: 'ונצואלה', definition: 'מדינה בדרום אמריקה עם נפט' },
            { solution: "צ'ילה", definition: 'מדינה בדרום אמריקה' },
            { solution: 'פרו', definition: 'מדינה בדרום אמריקה' },
            { solution: 'בוליביה', definition: 'מדינה בדרום אמריקה' },
        ],
    },
    {
        title: 'כללי',
        description: 'רשימה שמכילה כמה הגדרות כלליות שקשורות לישראל',
        words: [
            { solution: 'ירושלים', definition: 'בירת ישראל' },
            { solution: 'התיכון', definition: 'הים הגדול של ישראל' },
            { solution: 'תפוז', definition: 'פרי כתום שמתחיל באות תפ' },
            { solution: 'ברדלס', definition: 'החיה הכי מהירה ביבשה' },
            { solution: 'ירדן', definition: 'נהר שחוצה את ישראל' },
            { solution: 'ירוק', definition: 'צבע של דשא' },
            { solution: 'גיטרה', definition: 'כלי נגינה עם מיתרים' },
            { solution: 'תשרי', definition: 'החודש הראשון בלוח העברי' },
            { solution: 'פלאפל', definition: 'מאכל מחומוס' },
            { solution: 'לויתן', definition: 'יונק ימי גדול' },
            { solution: 'טלפון', definition: 'מכשיר לתקשורת' },
            { solution: 'כדורגל', definition: 'ספורט קבוצתי עם כדור' },
            { solution: 'פריז', definition: 'עיר הבירה של צרפת' },
            { solution: 'אדום', definition: 'צבע של דם' },
            { solution: 'קפה', definition: 'משקה חם עם קפאין' },
            { solution: 'כלב', definition: 'חיית מחמד שנובחת' },
            { solution: 'סכין', definition: 'כלי מטבח לחיתוך' },
            { solution: 'פסח', definition: "חג בו אוכלים מצות" },
            { solution: 'שמש', definition: 'הכוכב שסביבו מקיף כדור הארץ' },
            { solution: 'אפריקה', definition: 'היבשת שבה נמצאת מצרים' },
            { solution: 'חיפה', definition: 'עיר הנמל הראשית של ישראל' },
        ],
    },
]

export const SEED_CROSSWORD = {
    title: 'תשבץ לדוגמה',
    description: 'תשבץ שנוצר ע"י seed',
    size: 12,
    maxWords: 10,
}
